prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - prom.local
    tls:
      - secretName: prometheus-tls
        hosts:
          - prom.local
  prometheusSpec:
    retention: 15d
    nodeSelector:
      kubernetes.io/arch: arm64
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 10Gi

grafana:
  adminPassword: homelab
  nodeSelector:
    kubernetes.io/arch: arm64
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca
    hosts:
      - graf.local
    tls:
      - secretName: grafana-tls
        hosts:
          - graf.local

alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - alman.local
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alman.local
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/arch: arm64
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "null"
    receivers:
      - name: "null"

nodeExporter:
  enabled: true

kube-state-metrics:
  nodeSelector:
    kubernetes.io/arch: arm64

prometheusOperator:
  nodeSelector:
    kubernetes.io/arch: arm64