apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-secrets
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-client-secrets
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_CLIENT_SECRET
      remoteRef:
        key: keycloak
        property: grafana-client-secret
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        key: keycloak
        property: argocd-client-secret
