apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: test-standalone
  namespace: default
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi