server:
  nodeSelector:
    kubernetes.io/arch: arm64

  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address     = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "file" {
        path = "/vault/data"
      }

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: standard

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca
    hosts:
      - host: vault.homelab.local
        paths: []
    tls:
      - secretName: vault-tls
        hosts:
          - vault.homelab.local

ui:
  enabled: true
