nodeSelector:
  kubernetes.io/arch: arm64

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

webhook:
  nodeSelector:
    kubernetes.io/arch: arm64
  resources:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu: 100m
      memory: 128Mi

certController:
  nodeSelector:
    kubernetes.io/arch: arm64
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
