apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oauth
    creationPolicy: Owner
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: keycloak
        property: grafana-client-secret
