apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/lustoerk/k8ts.git
    targetRevision: main
    path: infra/seaweedfs
    directory:
      include: "ingress.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
